# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
permissions:
  contents: read
  secrets: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]
  schedule: # Run every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: go version

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -coverprofile=cover.out ./...

      - name: Test Coverage
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: go
          coverage-file: cover.out
          dsn: ${{ secrets.DEEPSOURCE_DSN }}

      - name: Update coverage report
        uses: ncruces/go-coverage-report@main
